# Generated by Django 5.1.5 on 2025-01-21 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://www.google.com/url?sa=i&url=https%3A%2F%2Forder.foodworks.org%2Floyalty&psig=AOvVaw0HZt3H7RZ4utMyEfTT0aXl&ust=1737546882976000&source=images&cd=vfe&opi=89978449&ved=0CBQQjRxqFwoTCMj_-NnghosDFQAAAAAdAAAAABAE', max_length=600),
        ),
    ]
